bases:
  - git::https://repo1.dso.mil/platform-one/big-bang/umbrella.git/base?ref=1.11.0

configMapGenerator:
  - name: common
    namespace: bigbang
    behavior: merge
    files:
      - values.yaml

patchesStrategicMerge:
- |-
  apiVersion: source.toolkit.fluxcd.io/v1beta1
  kind: GitRepository
  metadata:
    name: bigbang
    namespace: bigbang
  spec:
    ref:
      $patch: replace
      branch: "release-1.11.x"
      commit: "ac3d07ac0a5206b74478f6e41c58afa99363fa00" # tag 1.11.0
